server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: saturdaySpring
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

token:
  sign:
    secret-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855